# Learn Open CV

In [3]:

import cv2 as cv
import numpy as np

#### show image

In [3]:
img=cv.imread('Resources/1.jpg')
# print(img) 
cv.imshow('Image',img)
cv.waitKey(0)
cv.destroyAllWindows()

#### show video

In [4]:
cap_video=cv.VideoCapture('Resources/video_01.mp4')

while True:
    success,img=cap_video.read()
    cv.imshow('cap video',img)
    if cv.waitKey(1) & 0xFF== ord('q'):
        break
    
cap_video.release()
cv.destroyAllWindows()

#### Use Webcam

In [5]:


cap_webcam=cv.VideoCapture(0)
cap_webcam.set(3,640) # width
cap_webcam.set(4,450) #height
cap_webcam.set(10,100) #brightness


while True:
    success,img=cap_webcam.read()
    cv.imshow('cap webcam',img)
    if cv.waitKey(1) & 0xFF== ord('q'):
        break

cap_webcam.release()
cv.destroyAllWindows()

#### Basic functions

In [8]:
kernel=np.ones((5,5),np.uint8)
kernel

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [3]:
img=cv.imread('Resources/me.jpg')

In [17]:



img_gray=cv.cvtColor(img,cv.COLOR_BGR2GRAY)


img_blur_7=cv.GaussianBlur(img_gray,(7,7),0)
img_blur_3=cv.GaussianBlur(img_gray,(3,3),0)

img_canny_150_200=cv.Canny(img,150,200)
img_canny_50_50=cv.Canny(img,50,50)

img_dilation_7=cv.dilate(img_canny_150_200,np.ones((7,7),np.uint8),iterations=1)
img_dilation_2=cv.dilate(img_canny_150_200,np.ones((2,2),np.uint8),iterations=1)

img_eroded_1=cv.erode(img_dilation_7,np.ones((7,7),np.uint8),iterations=1)
img_eroded_2=cv.erode(img_dilation_7,np.ones((7,7),np.uint8),iterations=2)



# cv.imshow('Image',img)
# cv.imshow('Gray Image',img_gray)
# cv.imshow('Blur Image (kernel=7)',img_blur_7)
# cv.imshow('Blur Image (kernel=3)',img_blur_3)
cv.imshow('Canny Image (150-200)',img_canny_150_200)
# cv.imshow('Canny Image (50-50)',img_canny_50_50)

cv.imshow('Dilation Image (7)',img_dilation_7)
cv.imshow('Dilation Image (2)',img_dilation_2)

cv.imshow('Eroded Image (1)',img_eroded_1)
cv.imshow('Eroded Image (2)',img_eroded_2)

cv.imshow('Eroded Image (1)',img_eroded_1)
cv.imshow('Eroded Image (2)',img_eroded_2)
cv.waitKey(0)
cv.destroyAllWindows()

#### Resize and Cropping

In [2]:
img.shape
# (height , width , num of channel(BGR))

NameError: name 'img' is not defined

In [4]:

img_resize=cv.resize(img,(300,200))

cv.imshow('Image',img)
cv.imshow('Resize Image',img_resize)

cv.waitKey(0)
cv.destroyAllWindows()

In [5]:
img_resize.shape

(200, 300, 3)

In [6]:
img_cropped=img[80:500,180:500]
img_cropped.shape

(420, 320, 3)

In [7]:
cv.imshow('Cropped Image',img_cropped)
cv.waitKey(0)
cv.destroyAllWindows()

#### Shapes and Texts

In [2]:
img_black=np.zeros((512,512,3),np.uint8)
img_black.shape

(512, 512, 3)

In [3]:
img_blue=np.zeros((512,512,3),np.uint8)
img_blue[:]=[255,80,100]

In [4]:
img_blue_dark=np.zeros((512,512,3),np.uint8)
img_blue_dark[100:292,180:420]=[255,80,100]

In [9]:
def show_img(text,src):
    cv.imshow(text,src)
    cv.waitKey(0)
    cv.destroyAllWindows()

In [6]:
cv.imshow('Black Image',img_black)
cv.imshow('Blue Image',img_blue)
cv.imshow('Blue_Black Image',img_blue_dark)
cv.waitKey(0)
cv.destroyAllWindows()

In [10]:

img_blue=np.zeros((512,512,3),np.uint8)
img_blue[:]=[255,80,100]
# cv.line(img=img_blue
#,pt1=(0,0),pt2=(350,350),color=(100,200,200),thickness=5)
cv.line(img=img_blue,pt1=(0,0),
        pt2=(img_blue.shape[0],img_blue.shape[1]),
        color=(100,200,200),thickness=5)

show_img('Blue Image With Line',img_blue)


cv.rectangle(img_blue,(0,0),
        (250,250),
        (80,120,15),cv.FILLED)

show_img('Blue Image With Rectangle',img_blue) 

cv.circle(img=img_blue,center=(450,450),
          radius=50,
          color=(180,160,150),
          thickness=3)

show_img('Blue Image With Circle',img_blue) 

cv.putText(img=img_blue,text=' Open CV ',
           org=(150,120),fontFace=cv.FONT_HERSHEY_COMPLEX,
           fontScale=2,color=(170,219,9),thickness=2)
show_img('Blue Image With Text',img_blue)
 

#### Warp Perspective

In [15]:
img=cv.imread('Resources\playingcard.jpg')

In [21]:
width,height=(595,440)

pts1=np.float32([[336,100],[523,120],[496,334],[292,310]])
pts2=np.float32([[0,0],[width,0],[width,height],[0,height]])
matrix=cv.getPerspectiveTransform(pts1,pts2)
img_output=cv.warpPerspective(img,matrix,(width,height))

show_img('Cards Image',img)
show_img('Warp Image',img_output)

#### Joining Images

In [22]:
img=cv.imread('Resources\me.jpg')

numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

In [24]:
in_arr1 = np.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays horizontally
out_arr = np.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [26]:
imgHor=np.hstack((img,img))

show_img('Horizontal Images',imgHor)

In [27]:
imgVer=np.vstack((img,img))

show_img('Vertical Images',imgVer)

In [8]:
def stackImages(scale,imgArray):
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv.resize(imgArray[x][y], (imgArray[0][0].shape[1],
                                                                imgArray[0][0].shape[0]),None, scale, scale)
                if len(imgArray[x][y].shape) == 2: imgArray[x][y]= cv.cvtColor( imgArray[x][y], cv.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3), np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv.cvtColor(imgArray[x], cv.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver

In [31]:
imgGray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)

imgStack = stackImages(0.5,([img,imgGray,img],[img,img,img]))

show_img('Image Stack',imgStack)

#### Color Detection

In [2]:
img=cv.imread('Resources/4.jpg')

In [3]:
imgHSV=cv.cvtColor(img,cv.COLOR_BGR2HSV)

In [3]:
def empty(item):
    pass

In [7]:
cv.namedWindow('TrackBars')
cv.resizeWindow("TrackBars",640,240)

# before
# cv.createTrackbar('Hue Min','TrackBars',0,179,empty)
# cv.createTrackbar('Hue Max','TrackBars',179,179,empty)

# cv.createTrackbar('Sat Min','TrackBars',0,255,empty)
# cv.createTrackbar('Sat Max','TrackBars',255,255,empty)

# cv.createTrackbar('Val Min','TrackBars',0,255,empty)
# cv.createTrackbar('Val Max','TrackBars',255,255,empty)

# after
cv.createTrackbar('Hue Min','TrackBars',0,179,empty)
cv.createTrackbar('Hue Max','TrackBars',133,179,empty)

cv.createTrackbar('Sat Min','TrackBars',6,255,empty)
cv.createTrackbar('Sat Max','TrackBars',183,255,empty)

cv.createTrackbar('Val Min','TrackBars',109,255,empty)
cv.createTrackbar('Val Max','TrackBars',255,255,empty)

while True:
    img=cv.imread('Resources/lambo.jpg')
    img=cv.resize(img,(350,350))
    imgHSV=cv.cvtColor(img,cv.COLOR_BGR2HSV)
    
    
    h_min=cv.getTrackbarPos('Hue Min','TrackBars')
    h_max=cv.getTrackbarPos('Hue Max','TrackBars')
    
    s_min=cv.getTrackbarPos('Sat Min','TrackBars')
    s_max=cv.getTrackbarPos('Sat Max','TrackBars')
    
    v_min=cv.getTrackbarPos('Val Min','TrackBars')
    v_max=cv.getTrackbarPos('Val Max','TrackBars')
    
    print(f'h_min : {h_min} , h_max : {h_max} , s_min : {s_min} \
          ,s_max : {s_max} , v_min : {v_min} , v_max : {v_max}')
    
    lower=np.array([h_min,s_min,v_min])
    upper=np.array([h_max,s_max,v_max])
    mask=cv.inRange(imgHSV,lower,upper)
    img_result=cv.bitwise_and(img,img,mask=mask)
    
    img_stack=stackImages(0.6,([img,imgHSV],[mask,img_result]))
    cv.imshow('Stack Images',img_stack) 
    
    if cv.waitKey(1) & 0xFF== ord('q'):
        break
cv.destroyAllWindows()


h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6           ,s_max : 183 , v_min : 109 , v_max : 255
h_min : 0 , h_max : 133 , s_min : 6        

#### Contours / Shape Detection

I would explain a contour as “simply as a curve joining all the points lying on the boundary of that shape”.

 The cv2.approxPolyDP() takes an epsilon parameter whose value tells OpenCV,
 how much deviation we can allow from the original shape in order to receive our simplified contour

In [33]:

def getContours(img):
    contours,hierarchy=cv.findContours(img,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_NONE)
    for cnt in contours:
        area=cv.contourArea(cnt)
        print(area)
        if area > 500:
            cv.drawContours(img_contour,cnt,-1,(255,0,0),3)
            peri=cv.arcLength(cnt,True) #curve length 
            # print(peri)
            approx=cv.approxPolyDP(cnt,epsilon=0.02*peri,closed=True)
            # print(len(approx)) #3=> triangle #4 =>rectangle or Square #4> => curve
            obj_cor=len(approx)
            
            x,y,w,h=cv.boundingRect(approx)
            
            obj_type=''
            if obj_cor==3:
                obj_type='Triangle'
            elif obj_cor==4:
                asp_ratio=w/float(h)
                if asp_ratio >0.95 and asp_ratio < 1.05 :
                    obj_type='Square'
                else:
                    obj_type='Rectangle'
            else:
                obj_type='Curve'
            
            cv.rectangle(img_contour,(x,y),(x+w,y+h),(0,255,0),2)
            cv.putText(img_contour,obj_type,
                       (x+(w//2)-10,y+(h//2)),cv.FONT_HERSHEY_COMPLEX,0.7,
                       (56, 32, 24),2)            


In [34]:
img=cv.imread('Resources/shapes.jpg')
img=cv.resize(img,(450,450))
img_contour=img.copy()


img_gray=cv.cvtColor(img,cv.COLOR_BGR2GRAY)
img_blur=cv.GaussianBlur(img_gray,(7,7),1)

img_canny=cv.Canny(img_blur,50,50)
img_blank=np.zeros_like(img)

getContours(img_canny)

img_stack=stackImages(0.8,([img,img_gray,img_blur],
                           [img_canny,img_contour,img_blank]))
cv.imshow('Stack Images',img_stack) 
cv.waitKey(0)
cv.destroyAllWindows()

2231.0
5235.0
6464.0
6261.0
1016.5
6394.0
3968.5
3461.0
2112.0
1400.0
2175.0
5377.0
1648.0
3586.5
6257.0
3489.0


#### Face Detection

In [3]:
face_cascade=cv.CascadeClassifier('Resources\haarcascades\haarcascade_frontalface_default.xml')

In [18]:

img=cv.imread('Resources/lena.jpg')
img=cv.resize(img,(255,255))
img_gray=cv.cvtColor(img,cv.COLOR_BGR2GRAY)


faces=face_cascade.detectMultiScale(img_gray,1.1,4)

for (x,y,w,h) in faces:
    cv.rectangle(img_gray,(x,y),(x+w,y+h),(255,0,0),5)

cv.imshow('Image',img_gray)
cv.waitKey(0)
cv.destroyAllWindows()

#### Virtual Paint (Project 01)

In [8]:
cap_webcam=cv.VideoCapture(0)
cap_webcam.set(3,1200) # width
cap_webcam.set(4,1200) #height
cap_webcam.set(10,50) #brightness

# Red , Blue , Green
# my_colors=[[0,57,137,255,130,255],
#            [107,140,11,255,61,255],
#            [58,98,187,255,30,255]]

names=['Red' , 'Blue' , 'Green']

#BGR
my_colors=[[0,132,96,
            60,255,255],
           
           [112,103,0,
            179,255,255],
           
           [76,86,56,
            96,184,255]]

my_color_values=[[0,0,204],
                 [204,0,0],
                 [0,153,0]] 


my_points=[] # [x,y,color_name]

def findColor(img,colors,color_values):
    imgHSV=cv.cvtColor(img,cv.COLOR_BGR2HSV)
    new_points=[]
    for color,color_value in list(zip(my_colors,color_values)):
        lower=np.array(color[:3])
        upper=np.array(color[3:])
        mask=cv.inRange(imgHSV,lower,upper)
        x,y=getContours(mask)
        cv.circle(img_result,(x,y),10,color_value,cv.FILLED)
        if x!=0 and y!=0:
            new_points.append([x,y,color_value])
        # cv.imshow(f'{name} window',mask)
    return new_points


def getContours(img):
    contours,hierarchy=cv.findContours(img,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_NONE)
    x,y,w,h=0,0,0,0
    for cnt in contours:
        area=cv.contourArea(cnt)
        # print(area)
        if area > 500:
            # cv.drawContours(img_result,cnt,-1,(255,0,0),3)
            peri=cv.arcLength(cnt,True) #curve length 
            approx=cv.approxPolyDP(cnt,epsilon=0.02*peri,closed=True)
            x,y,w,h=cv.boundingRect(approx)
    return x+w//2,y
            
def drawOnCanvas(points):
    for point in points:
        cv.circle(img_result,(point[0],point[1]),18,point[2],cv.FILLED)










while True:
    success,img=cap_webcam.read()
    img_result=img.copy()
    new_points=findColor(img,my_colors,my_color_values)
    if len(new_points)!=0:
        for point in new_points:
            my_points.append(point)
            
    if len(my_points)!=0:
        drawOnCanvas(my_points)       
    cv.imshow('cap webcam',img_result)

    
    
    
    if cv.waitKey(1) & 0xFF== ord('q'):
        cv.destroyAllWindows()
        break

cap_webcam.release()


In [35]:
##### TODO: For Detect Color of Objects

cap_webcam=cv.VideoCapture(0)
cap_webcam.set(3,640) # width
cap_webcam.set(4,450) #height
cap_webcam.set(10,50) #brightness


def empty(item):
    pass


cv.namedWindow("HSV")
cv.resizeWindow("HSV",640,240)

# before
cv.createTrackbar('Hue Min','HSV',0,179,empty)
cv.createTrackbar('Hue Max','HSV',179,179,empty)

cv.createTrackbar('Sat Min','HSV',0,255,empty)
cv.createTrackbar('Sat Max','HSV',255,255,empty)

cv.createTrackbar('Val Min','HSV',0,255,empty)
cv.createTrackbar('Val Max','HSV',255,255,empty)

# # after
# cv.createTrackbar('Hue Min','TrackBars',0,179,empty)
# cv.createTrackbar('Hue Max','TrackBars',133,179,empty)

# cv.createTrackbar('Sat Min','TrackBars',6,255,empty)
# cv.createTrackbar('Sat Max','TrackBars',183,255,empty)

# cv.createTrackbar('Val Min','TrackBars',109,255,empty)
# cv.createTrackbar('Val Max','TrackBars',255,255,empty)

while True:
    _,img=cap_webcam.read()
    # cv.imshow('cap webcam',img)
    # img=cv.resize(img,(350,350))
    imgHSV=cv.cvtColor(img,cv.COLOR_BGR2HSV)
    
    
    h_min=cv.getTrackbarPos('Hue Min','HSV')
    h_max=cv.getTrackbarPos('Hue Max','HSV')
    
    s_min=cv.getTrackbarPos('Sat Min','HSV')
    s_max=cv.getTrackbarPos('Sat Max','HSV')
    
    v_min=cv.getTrackbarPos('Val Min','HSV')
    v_max=cv.getTrackbarPos('Val Max','HSV')
    
    # print(f'h_min : {h_min} , h_max : {h_max} , s_min : {s_min} \
    #       ,s_max : {s_max} , v_min : {v_min} , v_max : {v_max}')
    
    lower=np.array([h_min,s_min,v_min])
    upper=np.array([h_max,s_max,v_max])
    mask=cv.inRange(imgHSV,lower,upper)
    img_result=cv.bitwise_and(img,img,mask=mask)
    
    img_stack=stackImages(0.6,([img,imgHSV],[mask,img_result]))
    cv.imshow('Stack Images',img_stack) 
    
    if cv.waitKey(1) & 0xFF== ord('q'):
        break
cv.destroyAllWindows()
cap_webcam.release()


#### Document Scanner (Project 02)

In [10]:
width_img=640
height_img=480

cap_webcam=cv.VideoCapture(0)

ip_address='http://192.168.0.116:8080/video'
cap_webcam.open(ip_address)

cap_webcam.set(3,width_img) # width
cap_webcam.set(4,height_img) #height
cap_webcam.set(10,150) #brightness


def preProccessing(img):
    img_gray=cv.cvtColor(img,cv.COLOR_BGR2GRAY)
    img_blur=cv.GaussianBlur(img_gray,(5,5),1) ###
    # img_canny=cv.Canny(img_blur,20,20)##
    img_canny=cv.Canny(img_blur,50,50)##
    kernel=np.ones((5,5))
    img_dial=cv.dilate(img_canny,kernel,iterations=2)
    img_threshold =cv.erode(img_dial,kernel,iterations=1)
    
    return img_threshold
    

def getContours(img):
    biggest=np.array([])
    max_area=0
    x,y,w,h=(0,0,0,0)
    contours,hierarchy=cv.findContours(img,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_NONE)
    for cnt in contours:
        area=cv.contourArea(cnt)
        if area > 5000:
            # cv.drawContours(img_contour,cnt,-1,(255,0,0),3)
            peri=cv.arcLength(cnt,True) #curve length 
            approx=cv.approxPolyDP(cnt,epsilon=0.02*peri,closed=True)
            if area> max_area and len(approx)==4:
                biggest=approx
                max_area=area
                x,y,w,h=cv.boundingRect(approx)
                
    cv.drawContours(img_contour,biggest,-1,(255,0,0),20)
    cv.rectangle(img_contour,(x,y),(x+w,y+h),(0,255,0),5)
    
    return biggest       



def getWarp(img,biggest):

    pts1=np.float32(reorder(biggest))
    pts2=np.float32([[0,0],[width_img,0],[0,height_img],[width_img,height_img]])
    matrix=cv.getPerspectiveTransform(pts1,pts2)
    img_output=cv.warpPerspective(img,matrix,(width_img,height_img))
    img_cropped=img_output[20:img_output.shape[0]-20,20:img_output.shape[1]-20]
    img_resize=cv.resize(img_cropped,(width_img,height_img))
    return img_resize
    
def reorder(points):
    points=points.reshape((4,2))
    new_points=np.zeros((4,1,2),np.int32)
    
    add=points.sum(1)
    new_points[0]=points[np.argmin(add)]
    new_points[3]=points[np.argmax(add)]
    
    diff=np.diff(points,axis=1)
    new_points[1]=points[np.argmin(diff)]
    new_points[2]=points[np.argmax(diff)]
    
    return new_points
    











while True:
    _,img=cap_webcam.read()
    cv.resize(img,(width_img,height_img))
    img_contour=img.copy()
    img_threshold=preProccessing(img)
    biggest=getContours(img_threshold)
    if len(biggest)!=0:
        img_warped=getWarp(img,biggest)
        img_array=([img,img_threshold],
                   [img_contour,img_warped])
    else:
        img_array=([img,img_threshold],
                   [img,img])
    img_stack=stackImages(0.6,img_array)
    cv.imshow('Work Flow',img_stack)
    # print(biggest)
    # print('*'*25)
    cv.imshow('Scanner',img_contour)
    
    if cv.waitKey(1) & 0xFF== ord('q'):
        cv.destroyAllWindows()
        break

cap_webcam.release()